const $=id=>document.getElementById(id);
const state={view:'home',status:'Not started',signed:false,amendment:false,recording:false,recognition:null,mockTimer:null,audit:[],signedAt:null};
const fakeLines=['Client reported feeling overwhelmed this week due to work stress and difficulty sleeping.','Client described conflict with a coworker and increased worry before bed.','Therapist used CBT reframing and grounding practice during session.','Client reported the thought record was somewhat helpful.','Client appeared engaged and demonstrated insight into connection between sleep and mood.','Plan is to practice grounding before bed and continue CBT next session.'];
function init(){setToday();bind();setupSpeech();updateAll();audit('App opened');if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{})}
document.addEventListener('DOMContentLoaded',init);
function setToday(){$('sessionDate').value=new Date().toISOString().slice(0,10)}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>go(b.dataset.view));document.querySelectorAll('[data-goto]').forEach(b=>b.onclick=()=>go(b.dataset.goto));['clientSelect','sessionDate','noteType','sessionMode'].forEach(id=>$(id).onchange=updateAll);$('consentCheck').onchange=()=>{$('startRecordingBtn').disabled=!$('consentCheck').checked||state.recording};$('startRecordingBtn').onclick=startRecording;$('stopRecordingBtn').onclick=stopRecording;$('useTranscriptBtn').onclick=useTranscript;$('clearTranscriptBtn').onclick=()=>{$('transcriptText').value='';audit('Transcript cleared')};$('generateDraftBtn').onclick=generateDraft;$('signBtn').onclick=signNote;$('unlockBtn').onclick=()=>{$('amendmentPanel').classList.remove('hidden')};$('cancelUnlockBtn').onclick=()=>{$('amendmentPanel').classList.add('hidden');$('amendmentError').classList.add('hidden')};$('confirmUnlockBtn').onclick=unlockNote;$('copyBtn').onclick=copyNote;$('downloadTxtBtn').onclick=downloadTxt;$('downloadHtmlBtn').onclick=downloadHtml;$('loadMockEcwBtn').onclick=loadMockEcw;$('simulateEcwBtn').onclick=()=>{toast('Mock only — no data sent');$('mockEcwStatus').textContent='Mock only — no data sent. eCW writeback requires approved API access.';audit('Mock eCW send simulated')};$('copyAuditBtn').onclick=()=>navigator.clipboard?.writeText($('auditLog').textContent);$('resetBtn').onclick=resetDemo;window.addEventListener('online',updateNetwork);window.addEventListener('offline',updateNetwork);}
function go(view){state.view=view;document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(view+'View').classList.add('active');document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelector('.app-main').scrollTop=0;updateAll()}
function updateAll(){const client=$('clientSelect').value,date=$('sessionDate').value,type=$('noteType').value,mode=$('sessionMode').value;$('summaryClient').textContent=client;$('summaryDate').textContent=date||'—';$('summaryNoteType').textContent=type;$('summaryMode').textContent=mode;$('generateDraftBtn').textContent='Generate '+type+' Draft';$('sessionStatus').textContent=state.status;updateNetwork();updateProgress();$('pwaStatus').textContent=matchMedia('(display-mode: standalone)').matches?'Installed':'Browser mode'}
function updateNetwork(){const online=navigator.onLine;$('networkStatus').textContent=online?'Online':'Offline';$('networkStatus').className=online?'pill success':'pill warning'}
function updateProgress(){['stepCapture','stepDraft','stepSign','stepExport'].forEach(id=>$(id).classList.remove('active'));let id='stepCapture';if(state.status.includes('Draft'))id='stepDraft';if(state.status.includes('Signed'))id='stepSign';if(state.status.includes('export'))id='stepExport';$(id).classList.add('active');$('homeHeadline').textContent=state.status==='Not started'?'Start a demo session':state.status;}
function setupSpeech(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return;const r=new SR();r.continuous=true;r.interimResults=true;r.lang='en-US';r.onresult=e=>{let text='';for(let i=0;i<e.results.length;i++)text+=e.results[i][0].transcript+' ';$('transcriptText').value=text.trim()};r.onerror=()=>toast('Microphone unavailable. Using mock text is okay.');state.recognition=r}
function startRecording(){if(!$('consentCheck').checked)return;state.recording=true;state.status='Recording';$('recordingBadge').textContent='Recording';$('recordingBadge').className='pill danger';$('startRecordingBtn').disabled=true;$('stopRecordingBtn').disabled=false;$('transcriptText').value='';audit('Recording started');if(state.recognition){try{state.recognition.start()}catch{mockRecord()}}else mockRecord();updateAll()}
function mockRecord(){let i=0;state.mockTimer=setInterval(()=>{if(i<fakeLines.length){$('transcriptText').value+=($('transcriptText').value?'\n':'')+fakeLines[i++]}else stopRecording()},1300)}
function stopRecording(){state.recording=false;state.status='Transcript ready';$('recordingBadge').textContent='Transcript ready';$('recordingBadge').className='pill success';$('startRecordingBtn').disabled=!$('consentCheck').checked;$('stopRecordingBtn').disabled=true;if(state.mockTimer){clearInterval(state.mockTimer);state.mockTimer=null}try{state.recognition?.stop()}catch{}audit('Recording stopped / transcript ready');updateAll()}
function useTranscript(){const t=$('transcriptText').value.trim();if(!t)return toast('No transcript yet');$('roughNotes').value=($('roughNotes').value.trim()?$('roughNotes').value.trim()+'\n\n':'')+t;audit('Transcript moved into rough notes');toast('Transcript added')}
function generateDraft(){const rough=$('roughNotes').value.trim(),trans=$('transcriptText').value.trim();if(!rough&&!trans)return toast('Add rough notes or transcript first');const source=rough&&trans?'rough notes + transcript':rough?'rough notes':'transcript';const text=[rough,trans].filter(Boolean).join('\n');const type=$('noteType').value;const note=buildNote(type,text,source);$('draftNote').value=note;$('exportText').value=note;state.status='Draft ready';state.signed=false;state.amendment=false;$('draftNote').disabled=false;$('signBtn').classList.remove('hidden');$('unlockBtn').classList.add('hidden');$('draftStatus').textContent='Draft';$('draftStatus').className='pill';showQuality(text,source);audit('Draft generated: '+type);go('draft');toast('Draft generated. Review before signing.')}
function buildNote(type,text,source){const risk=analyzeRisk(text);const buckets=extract(text);const head=`[DRAFT — NOT SIGNED]\nClient: ${$('clientSelect').value}\nDate: ${$('sessionDate').value}\nFormat: ${type}\nSource: ${source}\n\n`;let body='';if(type==='SOAP')body=`SUBJECTIVE:\n${buckets.subjective}\n\nOBJECTIVE:\n${buckets.objective}\n\nASSESSMENT:\n${buckets.assessment}\n\nPLAN:\n${buckets.plan}`;else if(type==='DAP')body=`DATA:\n${buckets.subjective}\n${buckets.objective}\n\nASSESSMENT:\n${buckets.assessment}\n\nPLAN:\n${buckets.plan}`;else if(type==='BIRP')body=`BEHAVIOR:\n${buckets.subjective}\n${buckets.objective}\n\nINTERVENTION:\n${buckets.intervention}\n\nRESPONSE:\n${buckets.assessment}\n\nPLAN:\n${buckets.plan}`;else body=`SESSION SUMMARY:\n${buckets.subjective}\n\nINTERVENTIONS USED:\n${buckets.intervention}\n\nCLIENT RESPONSE:\n${buckets.assessment}\n\nPLAN:\n${buckets.plan}`;return head+body+`\n\nRISK / SAFETY:\n${risk}\n\nPROTOTYPE ONLY — therapist must review, edit, and verify before entering into EHR.`}
function extract(text){const lines=text.split(/[\n.]+/).map(x=>x.trim()).filter(Boolean);const has=w=>new RegExp(w,'i').test(text);const pick=keys=>lines.filter(l=>keys.some(k=>l.toLowerCase().includes(k))).join('. ');return{subjective:pick(['reported','stated','felt','feeling','worry','anxiety','stress','sleep','sad','depress','conflict'])||'[Therapist to add client report and presenting concerns]',objective:pick(['appeared','observed','engaged','speech','affect','mood','presentation','demonstrated'])||'Client presentation not clearly documented in source text. Therapist to add observations.',intervention:pick(['cbt','grounding','breathing','reframing','thought record','psychoeducation','mindfulness','skills','intervention','practiced'])||'[Therapist to add interventions used]',assessment:pick(['insight','progress','helpful','improved','barrier','motivation','demonstrated'])||'Draft interpretation: therapist to clarify clinical assessment and progress toward goals.',plan:pick(['plan','homework','continue','next session','practice','referral','follow'])||'[Therapist to add plan, homework, and follow-up focus]'} }
function analyzeRisk(text){const lower=text.toLowerCase();const riskWords=['suicide','suicidal','si','self-harm','self harm','homicidal','hi','harm','danger','safety'];const detected=riskWords.some(w=>lower.includes(w));const denial=/(denied|denies|no)\s+(suicidal|suicide|si|self[- ]harm|homicidal|hi)/i.test(text);if(denial)return 'Source text indicates client denied SI/HI/self-harm. Therapist must verify before signing.';if(detected)return 'Risk/safety language detected in source text. Therapist must assess, clarify, and verify before signing.';return 'No risk/safety concerns documented in source text. Therapist must verify before signing.'}
function showQuality(text,source){$('qualityPanel').classList.remove('hidden');$('qualitySource').textContent=source;const words=text.split(/\s+/).filter(Boolean).length;$('qualityCompleteness').textContent=words>80?'High':words>35?'Medium':'Low';$('qualityRisk').textContent=analyzeRisk(text).startsWith('No risk')?'No':'Yes'}
function signNote(){if(!$('draftNote').value.trim())return toast('Generate a draft first');state.signed=true;state.signedAt=new Date().toLocaleString();state.status='Signed';$('draftNote').value=$('draftNote').value.replace('[DRAFT — NOT SIGNED]','[SIGNED — '+state.signedAt+']');$('draftNote').disabled=true;$('exportText').value=$('draftNote').value;$('draftStatus').textContent='Signed / Locked';$('draftStatus').className='pill success';$('signedInfo').textContent='Signed '+state.signedAt+' by demo provider';$('signedInfo').classList.remove('hidden');$('signBtn').classList.add('hidden');$('unlockBtn').classList.remove('hidden');audit('Note signed and locked');toast('Signed and locked');updateAll()}
function unlockNote(){const r=$('amendmentReason').value.trim();if(!r){$('amendmentError').classList.remove('hidden');return}state.signed=false;state.amendment=true;state.status='Amendment mode';$('draftNote').disabled=false;$('draftNote').value=$('draftNote').value.replace(/\[SIGNED[^\]]+\]/,'[AMENDMENT MODE]');$('draftStatus').textContent='Amendment';$('draftStatus').className='pill warning';$('signBtn').classList.remove('hidden');$('unlockBtn').classList.add('hidden');$('amendmentPanel').classList.add('hidden');audit('Note unlocked for amendment. Reason documented, not logged.');toast('Amendment mode active');updateAll()}
function copyNote(){const text=$('exportText').value.trim();if(!text)return toast('No note to copy');navigator.clipboard?.writeText(text).then(()=>toast('Copied for eCW')).catch(()=>toast('Select and copy manually'));audit('Note copied for eCW')}
function downloadTxt(){download('lcsw-note.txt',$('exportText').value,'text/plain');audit('TXT downloaded')}
function downloadHtml(){download('lcsw-note.html','<pre>'+escapeHtml($('exportText').value)+'</pre>','text/html');audit('Printable HTML downloaded')}
function download(name,content,type){if(!content)return toast('No note to download');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function loadMockEcw(){$('mockPatient').textContent='PT-00042';$('mockAppt').textContent=$('sessionDate').value;$('mockProvider').textContent='Jane Smith, LCSW';$('mockEncounter').textContent='Individual therapy';audit('Mock eCW context loaded')}
function audit(msg){state.audit.push({time:new Date().toLocaleTimeString(),msg});$('auditLog').textContent=state.audit.map(a=>`[${a.time}] ${a.msg}`).join('\n')}
function resetDemo(){['transcriptText','roughNotes','draftNote','exportText','amendmentReason'].forEach(id=>$(id).value='');state.status='Not started';state.signed=false;state.amendment=false;state.audit=[];$('qualityPanel').classList.add('hidden');$('signedInfo').classList.add('hidden');$('signBtn').classList.remove('hidden');$('unlockBtn').classList.add('hidden');audit('Demo session reset');updateAll();toast('Reset complete')}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function escapeHtml(s){return String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}