const $=id=>document.getElementById(id);
const state={view:'home',status:'Not started',signed:false,amendment:false,recording:false,recognition:null,mockTimer:null,audit:[],signedAt:null};
const fakeLines=['Client reported feeling overwhelmed this week due to work stress and difficulty sleeping.','Client described conflict with a coworker and increased worry before bed.','Therapist used CBT reframing and grounding practice during session.','Client reported the thought record was somewhat helpful.','Client appeared engaged and demonstrated insight into connection between sleep and mood.','Plan is to practice grounding before bed and continue CBT next session.'];
function init(){setToday();bind();setupSpeech();updateAll();audit('App opened');if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{})}
document.addEventListener('DOMContentLoaded',init);
function setToday(){$('sessionDate').value=new Date().toISOString().slice(0,10)}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>go(b.dataset.view));document.querySelectorAll('[data-goto]').forEach(b=>b.onclick=()=>go(b.dataset.goto));['clientSelect','sessionDate','noteType','sessionMode'].forEach(id=>$(id).onchange=updateAll);$('consentCheck').onchange=()=>{$('startRecordingBtn').disabled=!$('consentCheck').checked||state.recording};$('startRecordingBtn').onclick=startRecording;$('stopRecordingBtn').onclick=stopRecording;$('useTranscriptBtn').onclick=useTranscript;$('clearTranscriptBtn').onclick=()=>{$('transcriptText').value='';audit('Transcript cleared')};$('generateDraftBtn').onclick=generateDraft;$('signBtn').onclick=signNote;$('unlockBtn').onclick=()=>{$('amendmentPanel').classList.remove('hidden')};$('cancelUnlockBtn').onclick=()=>{$('amendmentPanel').classList.add('hidden');$('amendmentError').classList.add('hidden')};$('confirmUnlockBtn').onclick=unlockNote;$('copyBtn').onclick=copyNote;$('downloadTxtBtn').onclick=downloadTxt;$('downloadHtmlBtn').onclick=downloadHtml;$('loadMockEcwBtn').onclick=loadMockEcw;$('simulateEcwBtn').onclick=()=>{toast('Mock only — no data sent');$('mockEcwStatus').textContent='Mock only — no data sent. eCW writeback requires approved API access.';audit('Mock eCW send simulated')};$('copyAuditBtn').onclick=()=>navigator.clipboard?.writeText($('auditLog').textContent);$('resetBtn').onclick=resetDemo;window.addEventListener('online',updateNetwork);window.addEventListener('offline',updateNetwork);}
function go(view){state.view=view;document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(view+'View').classList.add('active');document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelector('.app-main').scrollTop=0;updateAll()}
function updateAll(){const client=$('clientSelect').value,date=$('sessionDate').value,type=$('noteType').value,mode=$('sessionMode').value;$('summaryClient').textContent=client;$('summaryDate').textContent=date||'—';$('summaryNoteType').textContent=type;$('summaryMode').textContent=mode;$('generateDraftBtn').textContent='Generate '+type+' Draft';$('sessionStatus').textContent=state.status;updateNetwork();updateProgress();$('pwaStatus').textContent=matchMedia('(display-mode: standalone)').matches?'Installed':'Browser mode'}
function updateNetwork(){const online=navigator.onLine;$('networkStatus').textContent=online?'Online':'Offline';$('networkStatus').className=online?'pill success':'pill warning'}
function updateProgress(){['stepCapture','stepDraft','stepSign','stepExport'].forEach(id=>$(id).classList.remove('active'));let id='stepCapture';if(state.status.includes('Draft'))id='stepDraft';if(state.status.includes('Signed'))id='stepSign';if(state.status.includes('export'))id='stepExport';$(id).classList.add('active');$('homeHeadline').textContent=state.status==='Not started'?'Start a demo session':state.status;}
function setupSpeech(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){audit('Browser speech recognition unavailable — use phone dictation or mock transcript');return}const r=new SR();r.continuous=true;r.interimResults=true;r.lang='en-US';r.onresult=e=>{let text='';for(let i=0;i<e.results.length;i++)text+=e.results[i][0].transcript+' ';$('transcriptText').value=text.trim();state.status='Transcript ready';updateAll()};r.onerror=()=>{toast('Browser transcription failed. Use iPhone dictation into the transcript box.');audit('Browser transcription error')};state.recognition=r}
function startRecording(){if(!$('consentCheck').checked)return;state.recording=true;state.status='Recording';$('recordingBadge').textContent='Recording';$('recordingBadge').className='pill danger';$('startRecordingBtn').disabled=true;$('stopRecordingBtn').disabled=false;$('transcriptText').value='';audit('Recording started');if(state.recognition){try{state.recognition.start()}catch{mockRecord('Browser transcription failed — using demo transcript.')}}else mockRecord('Browser transcription is not supported here — using demo transcript. For real testing on iPhone, tap into Transcript or Rough Notes and use the keyboard microphone dictation.');updateAll()}
function mockRecord(reason){toast(reason||'Using demo transcript');audit(reason||'Mock transcript started');let i=0;state.mockTimer=setInterval(()=>{if(i<fakeLines.length){$('transcriptText').value+=($('transcriptText').value?'\n':'')+fakeLines[i++]}else stopRecording()},700)}
function stopRecording(){state.recording=false;state.status='Transcript ready';$('recordingBadge').textContent='Transcript ready';$('recordingBadge').className='pill success';$('startRecordingBtn').disabled=!$('consentCheck').checked;$('stopRecordingBtn').disabled=true;if(state.mockTimer){clearInterval(state.mockTimer);state.mockTimer=null}try{state.recognition?.stop()}catch{}audit('Recording stopped / transcript ready');updateAll()}
function useTranscript(){const t=$('transcriptText').value.trim();if(!t)return toast('No transcript yet');$('roughNotes').value=($('roughNotes').value.trim()?$('roughNotes').value.trim()+'\n\n':'')+t;audit('Transcript moved into rough notes');toast('Transcript added')}
function generateDraft(){const rough=$('roughNotes').value.trim(),trans=$('transcriptText').value.trim();if(!rough&&!trans)return toast('Nothing to summarize. Dictate/type into Transcript or Rough Notes first.');const source=rough&&trans?'rough notes + transcript':rough?'rough notes':'transcript';const text=[rough,trans].filter(Boolean).join('\n');const type=$('noteType').value;const note=buildNote(type,text,source);$('draftNote').value=note;$('exportText').value=note;state.status='Draft ready';state.signed=false;state.amendment=false;$('draftNote').disabled=false;$('signBtn').classList.remove('hidden');$('unlockBtn').classList.add('hidden');$('draftStatus').textContent='Draft';$('draftStatus').className='pill';showQuality(text,source);audit('Draft generated: '+type);go('draft');toast('Draft generated. Review before signing.')}
function buildNote(type,text,source){const risk=analyzeRisk(text);const buckets=extract(text);const head=`[DRAFT — NOT SIGNED]\nClient: ${$('clientSelect').value}\nDate: ${$('sessionDate').value}\nFormat: ${type}\nSource: ${source}\n\n`;let body='';if(type==='SOAP')body=`SUBJECTIVE:\n${buckets.subjective}\n\nOBJECTIVE:\n${buckets.objective}\n\nASSESSMENT:\n${buckets.assessment}\n\nPLAN:\n${buckets.plan}`;else if(type==='DAP')body=`DATA:\n${buckets.data}\n\nASSESSMENT:\n${buckets.assessment}\n\nPLAN:\n${buckets.plan}`;else if(type==='BIRP')body=`BEHAVIOR:\n${buckets.behavior}\n\nINTERVENTION:\n${buckets.intervention}\n\nRESPONSE:\n${buckets.response}\n\nPLAN:\n${buckets.plan}`;else body=`SESSION SUMMARY:\n${buckets.summary}\n\nINTERVENTIONS USED:\n${buckets.intervention}\n\nCLIENT RESPONSE:\n${buckets.response}\n\nPLAN:\n${buckets.plan}`;return head+body+`\n\nRISK / SAFETY:\n${risk}\n\nPROTOTYPE ONLY — therapist must review, edit, and verify before entering into EHR.`}
function splitSentences(text){return text.replace(/\s+/g,' ').split(/(?<=[.!?])\s+|\n+/).map(s=>s.trim()).filter(Boolean)}
function includesAny(s,keys){const lower=s.toLowerCase();return keys.some(k=>lower.includes(k))}
function formatList(items,fallback){return items.length?items.map(x=>'• '+x.replace(/[.]+$/,'')).join('\n'):fallback}
function extract(text){const lines=splitSentences(text);const subjective=lines.filter(l=>includesAny(l,['reported','stated','said','felt','feeling','worry','anxiety','stress','sleep','sad','depress','conflict','overwhelmed','concern','goal','issue','problem']));const objective=lines.filter(l=>includesAny(l,['appeared','observed','engaged','speech','affect','mood','presentation','demonstrated','participated','tearful','calm','agitated','oriented']));const intervention=lines.filter(l=>includesAny(l,['cbt','grounding','breathing','reframing','thought record','psychoeducation','mindfulness','skills','intervention','practiced','processed','explored','role play','validated','supportive']));const assessment=lines.filter(l=>includesAny(l,['insight','progress','helpful','improved','barrier','motivation','demonstrated','increased','decreased','continues','difficulty','symptoms','pattern']));const plan=lines.filter(l=>includesAny(l,['plan','homework','continue','next session','practice','referral','follow','schedule','before bed','between sessions']));const allSummary=formatList(lines.slice(0,6),'• Source text was too sparse. Therapist to add clinically relevant summary.');return{subjective:formatList(subjective.length?subjective:lines.slice(0,4),'• Client report was not clearly separated in source text. Therapist to clarify presenting concerns.'),objective:formatList(objective,'• Objective observations were not captured in the source text. Therapist to add appearance, affect, behavior, speech, and engagement.'),intervention:formatList(intervention,'• Interventions were not clearly documented in source text. Therapist to add modality and specific interventions used.'),assessment:formatList(assessment.length?assessment:lines.slice(0,3),'• Draft interpretation pending. Therapist to clarify clinical assessment and progress toward goals.'),plan:formatList(plan,'• Plan not clearly documented in source text. Therapist to add homework, follow-up focus, and next steps.'),data:allSummary,behavior:formatList([...subjective,...objective].length?[...subjective,...objective]:lines.slice(0,5),'• Behavior/presentation not clearly documented. Therapist to clarify.'),response:formatList(assessment.length?assessment:lines.filter(l=>includesAny(l,['helpful','engaged','responded','receptive','insight'])).slice(0,3),'• Client response not clearly documented. Therapist to clarify engagement, insight, and response.'),summary:allSummary}}
function analyzeRisk(text){const lower=' '+text.toLowerCase()+' ';const denial=/(denied|denies|no|without)\s+(current\s+)?(suicidal ideation|suicide|si\b|s\/i|self[- ]harm|homicidal ideation|hi\b|h\/i)/i.test(text);const risk=/(\bsuicid(e|al)\b|\bsi\b|s\/i|self[- ]harm|\bhomicid(e|al)\b|\bhi\b|h\/i|\bdanger\b|\bsafety concern\b|\bcrisis\b|\bintent\b|\bplan to harm\b)/i.test(text);if(denial)return 'Source text indicates client denied SI/HI/self-harm. Therapist must verify before signing.';if(risk)return 'Risk/safety language detected in source text. Therapist must assess, clarify, and verify before signing.';return 'No risk/safety concerns documented in source text. Therapist must verify before signing.'}
function showQuality(text,source){$('qualityPanel').classList.remove('hidden');$('qualitySource').textContent=source;const words=text.split(/\s+/).filter(Boolean).length;$('qualityCompleteness').textContent=words>80?'High':words>35?'Medium':'Low';$('qualityRisk').textContent=analyzeRisk(text).startsWith('No risk')?'No':'Yes'}
function signNote(){if(!$('draftNote').value.trim())return toast('Generate a draft first');state.signed=true;state.signedAt=new Date().toLocaleString();state.status='Signed';$('draftNote').value=$('draftNote').value.replace('[DRAFT — NOT SIGNED]','[SIGNED — '+state.signedAt+']');$('draftNote').disabled=true;$('exportText').value=$('draftNote').value;$('draftStatus').textContent='Signed / Locked';$('draftStatus').className='pill success';$('signedInfo').textContent='Signed '+state.signedAt+' by demo provider';$('signedInfo').classList.remove('hidden');$('signBtn').classList.add('hidden');$('unlockBtn').classList.remove('hidden');audit('Note signed and locked');toast('Signed and locked');updateAll()}
function unlockNote(){const r=$('amendmentReason').value.trim();if(!r){$('amendmentError').classList.remove('hidden');return}state.signed=false;state.amendment=true;state.status='Amendment mode';$('draftNote').disabled=false;$('draftNote').value=$('draftNote').value.replace(/\[SIGNED[^\]]+\]/,'[AMENDMENT MODE]');$('draftStatus').textContent='Amendment';$('draftStatus').className='pill warning';$('signBtn').classList.remove('hidden');$('unlockBtn').classList.add('hidden');$('amendmentPanel').classList.add('hidden');audit('Note unlocked for amendment. Reason documented, not logged.');toast('Amendment mode active');updateAll()}
function copyNote(){const text=$('exportText').value.trim();if(!text)return toast('No note to copy');navigator.clipboard?.writeText(text).then(()=>toast('Copied for eCW')).catch(()=>toast('Select and copy manually'));audit('Note copied for eCW')}
function downloadTxt(){download('lcsw-note.txt',$('exportText').value,'text/plain');audit('TXT downloaded')}
function downloadHtml(){download('lcsw-note.html','<pre>'+escapeHtml($('exportText').value)+'</pre>','text/html');audit('Printable HTML downloaded')}
function download(name,content,type){if(!content)return toast('No note to download');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function loadMockEcw(){$('mockPatient').textContent='PT-00042';$('mockAppt').textContent=$('sessionDate').value;$('mockProvider').textContent='Jane Smith, LCSW';$('mockEncounter').textContent='Individual therapy';audit('Mock eCW context loaded')}
function audit(msg){state.audit.push({time:new Date().toLocaleTimeString(),msg});$('auditLog').textContent=state.audit.map(a=>`[${a.time}] ${a.msg}`).join('\n')}
function resetDemo(){['transcriptText','roughNotes','draftNote','exportText','amendmentReason'].forEach(id=>$(id).value='');state.status='Not started';state.signed=false;state.amendment=false;state.audit=[];$('qualityPanel').classList.add('hidden');$('signedInfo').classList.add('hidden');$('signBtn').classList.remove('hidden');$('unlockBtn').classList.add('hidden');audit('Demo session reset');updateAll();toast('Reset complete')}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function escapeHtml(s){return String(s).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}